chore(deps): bump langchain-community from 0.3.23 to 0.3.27 in /handler-py/rocketnotes_handler/handler_semantic_search (#229)
Bumps [langchain-community](https://github.com/langchain-ai/langchain)
from 0.3.23 to 0.3.27.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/langchain-ai/langchain/releases">langchain-community's
releases</a>.</em></p>
<blockquote>
<h2>langchain-openai==0.3.27</h2>
<p>Changes since langchain-openai==0.3.26</p>
<p>openai: release 0.3.27 (<a
href="https://redirect.github.com/langchain-ai/langchain/issues/31769">#31769</a>)
openai[fix]: Correctly set usage metadata for OpenAI Responses API (<a
href="https://redirect.github.com/langchain-ai/langchain/issues/31756">#31756</a>)
docs: updates from langchain-openai 0.3.26 (<a
href="https://redirect.github.com/langchain-ai/langchain/issues/31764">#31764</a>)</p>
<h2>langchain==0.3.27</h2>
<p>Changes since langchain==0.3.26</p>
<p>fix(langchain): update deps
release(langchain): 0.3.27 (<a
href="https://redirect.github.com/langchain-ai/langchain/issues/32227">#32227</a>)
feat(langchain): add ruff rules PL (<a
href="https://redirect.github.com/langchain-ai/langchain/issues/32079">#32079</a>)
docs: formatting cleanup (<a
href="https://redirect.github.com/langchain-ai/langchain/issues/32188">#32188</a>)
fix: replace deprecated <code>Pydantic .schema()</code> calls with v1/v2
compatible pattern (<a
href="https://redirect.github.com/langchain-ai/langchain/issues/32162">#32162</a>)
feat(langchain): add ruff rules TRY (<a
href="https://redirect.github.com/langchain-ai/langchain/issues/32047">#32047</a>)
feat(langchain): add ruff rules PT (<a
href="https://redirect.github.com/langchain-ai/langchain/issues/32010">#32010</a>)
fix(ollama): robustly parse single-quoted JSON in tool calls (<a
href="https://redirect.github.com/langchain-ai/langchain/issues/32109">#32109</a>)
fix(core): JSON Schema reference resolution for list indices (<a
href="https://redirect.github.com/langchain-ai/langchain/issues/32088">#32088</a>)
refactor(langchain): remove <code>model_rebuild</code> (<a
href="https://redirect.github.com/langchain-ai/langchain/issues/32080">#32080</a>)
feat(langchain): add ruff rules G (<a
href="https://redirect.github.com/langchain-ai/langchain/issues/32029">#32029</a>)
feat(langchain): add ruff rules DTZ (<a
href="https://redirect.github.com/langchain-ai/langchain/issues/32021">#32021</a>)
feat(langchain): add ruff rules PTH (<a
href="https://redirect.github.com/langchain-ai/langchain/issues/32008">#32008</a>)
chore: update error message formatting (<a
href="https://redirect.github.com/langchain-ai/langchain/issues/31980">#31980</a>)
docs: add Google-style docstrings to tools and llms modules (zapier, …
(<a
href="https://redirect.github.com/langchain-ai/langchain/issues/31957">#31957</a>)
chore[langchain]: fix broad base except in crawler.py (<a
href="https://redirect.github.com/langchain-ai/langchain/issues/31941">#31941</a>)
ruff: restore stacklevels, disable autofixing (<a
href="https://redirect.github.com/langchain-ai/langchain/issues/31919">#31919</a>)
ruff: add bugbear across packages (<a
href="https://redirect.github.com/langchain-ai/langchain/issues/31917">#31917</a>)
exception: update Exception to ValueError for clearer error handling (<a
href="https://redirect.github.com/langchain-ai/langchain/issues/31915">#31915</a>)
langchain[patch]: harden xml parser for xmloutput agent (<a
href="https://redirect.github.com/langchain-ai/langchain/issues/31859">#31859</a>)
langchain: Add ruff rules B (<a
href="https://redirect.github.com/langchain-ai/langchain/issues/31908">#31908</a>)
langchain: Fix Evaluator's _check_evaluation_args (<a
href="https://redirect.github.com/langchain-ai/langchain/issues/31910">#31910</a>)
langchain: Use pytest.raises and pytest.fail to handle exceptions in
tests (<a
href="https://redirect.github.com/langchain-ai/langchain/issues/31911">#31911</a>)
huggingface[patch]: ruff fixes and rules (<a
href="https://redirect.github.com/langchain-ai/langchain/issues/31912">#31912</a>)
anthropic[patch]: ruff fixes and rules (<a
href="https://redirect.github.com/langchain-ai/langchain/issues/31899">#31899</a>)
ruff: more rules across the board &amp; fixes (<a
href="https://redirect.github.com/langchain-ai/langchain/issues/31898">#31898</a>)
fix: automatically fix issues with ruff (<a
href="https://redirect.github.com/langchain-ai/langchain/issues/31897">#31897</a>)
fix: complete exception handling for UpstashRedisEntityStore (<a
href="https://redirect.github.com/langchain-ai/langchain/issues/31893">#31893</a>)
fix: lint/format (<a
href="https://redirect.github.com/langchain-ai/langchain/issues/31894">#31894</a>)
langchain: Add ruff rule RUF (<a
href="https://redirect.github.com/langchain-ai/langchain/issues/31874">#31874</a>)
langchain: Add ruff rules FBT (<a
href="https://redirect.github.com/langchain-ai/langchain/issues/31885">#31885</a>)
langchain: Add ruff rule RET (<a
href="https://redirect.github.com/langchain-ai/langchain/issues/31875">#31875</a>)
langchain: Add ruff rules C4 (<a
href="https://redirect.github.com/langchain-ai/langchain/issues/31879">#31879</a>)
langchain: Add ruff rules SIM (<a
href="https://redirect.github.com/langchain-ai/langchain/issues/31881">#31881</a>)
langchain: Add ruff rules A (<a
href="https://redirect.github.com/langchain-ai/langchain/issues/31888">#31888</a>)
langchain: Add ruff rules EM (<a
href="https://redirect.github.com/langchain-ai/langchain/issues/31873">#31873</a>)
langchain: Add ruff rules PIE (<a
href="https://redirect.github.com/langchain-ai/langchain/issues/31880">#31880</a>)
langchain: Add ruff rule W (<a
href="https://redirect.github.com/langchain-ai/langchain/issues/31876">#31876</a>)
langchain: Bump ruff version to 0.12 (<a
href="https://redirect.github.com/langchain-ai/langchain/issues/31867">#31867</a>)
langchain[patch]: fix a bug where <code>now.replace(day=now.day -
1)</code> would raise a <code>ValueError</code> when
<code>now.day</code> is equal to 1 (<a
href="https://redirect.github.com/langchain-ai/langchain/issues/31878">#31878</a>)</p>
<!-- raw HTML omitted -->
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/langchain-ai/langchain/commit/bdf1cd383ce36dc18381a3bf3fb0a579337a32b5"><code>bdf1cd3</code></a>
fix(langchain): update deps</li>
<li><a
href="https://github.com/langchain-ai/langchain/commit/77c981999ef9db9a2fcc9feb76576cc035ae40fc"><code>77c9819</code></a>
fix(text-splitters): update langchain-core version to 0.3.72</li>
<li><a
href="https://github.com/langchain-ai/langchain/commit/7f015b6f144ba5edfc9e35acf3cb663ec6020345"><code>7f015b6</code></a>
fix(text-splitters): update lock for release</li>
<li><a
href="https://github.com/langchain-ai/langchain/commit/71ad451e1f44de6306b796204f1c03026a5bd470"><code>71ad451</code></a>
Merge branch 'master' of github.com:langchain-ai/langchain</li>
<li><a
href="https://github.com/langchain-ai/langchain/commit/2c428937039dc2b97877a44e1cd0416a4e69d205"><code>2c42893</code></a>
fix(langchain): update langchain-core version to 0.3.72</li>
<li><a
href="https://github.com/langchain-ai/langchain/commit/0e139fb9a6eed22be90772822081df90c6d81f5b"><code>0e139fb</code></a>
release(langchain): 0.3.27 (<a
href="https://redirect.github.com/langchain-ai/langchain/issues/32227">#32227</a>)</li>
<li><a
href="https://github.com/langchain-ai/langchain/commit/622bb0575137d883c785e776e1120541a3b286c3"><code>622bb05</code></a>
fix(langchain): class HTMLSemanticPreservingSplitter ignores the text
inside ...</li>
<li><a
href="https://github.com/langchain-ai/langchain/commit/56dde3ade3b6b979f5c1f043c2c8b4a8db82f867"><code>56dde3a</code></a>
feat(langchain): v1 scaffolding (<a
href="https://redirect.github.com/langchain-ai/langchain/issues/32166">#32166</a>)</li>
<li><a
href="https://github.com/langchain-ai/langchain/commit/bd3d6496f3c67c8be10df0847ee346c9379f7169"><code>bd3d649</code></a>
release(core): 0.3.72 (<a
href="https://redirect.github.com/langchain-ai/langchain/issues/32214">#32214</a>)</li>
<li><a
href="https://github.com/langchain-ai/langchain/commit/fb5da8384e636db91b0313cab3cc21b661889684"><code>fb5da83</code></a>
fix(core): Dereference Refs for pydantic schema fails in tool schema
generati...</li>
<li>Additional commits viewable in <a
href="https://github.com/langchain-ai/langchain/compare/langchain==0.3.23...langchain==0.3.27">compare
view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility
score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=langchain-community&package-manager=pip&previous-version=0.3.23&new-version=0.3.27)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore this major version` will close this PR and stop
Dependabot creating any more for this major version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop
Dependabot creating any more for this minor version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop
Dependabot creating any more for this dependency (unless you reopen the
PR or upgrade to it yourself)
You can disable automated security fix PRs for this repo from the
[Security Alerts
page](https://github.com/fynnfluegge/rocketnotes/network/alerts).

</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>